---
title: Orbits
author: Arnaud Fournier
email: arnaud@orbits.io
description: Orbital Marketing is a digital marketing agency that supports your business
  by taking over your marketing accounts and providing strategic consultancy.
baseurl: "/"
url: ''
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
